### ISSUE TITLE
An AttributeError: 'int' object has no attribute 'data'

### ISSUE THREAD

**Issue by makabaka987** [deepakn97/relationPrediction#11]
Initialised relations and entities from TransE
Traceback (most recent call last):
  File "main.py", line 110, in <module>
    Corpus_, entity_embeddings, relation_embeddings = load_data(args)
  File "main.py", line 105, in load_data
    args.batch_size_gat, args.valid_invalid_ratio_gat, unique_entities_train, args.get_2hop)
  File "/home/KBAT-master/create_batch.py", line 35, in __init__
    self.graph = self.get_graph()
  File "/home/KBAT-master/create_batch.py", line 234, in get_graph
    source = data[1].data.item()
AttributeError: 'int' object has no attribute 'data'

**Comment by deepakn97** [comment]
It seems like the code is not able to acces any CUDA devices. Please activate the conda environment or check your installation of your CUDA. 
I am closing this issue, please feel free to re-open it in case you have more questions.
Sorry for the extremely late reply.

**Comment by makabaka987** [comment]
Thank you very much for your reply. I would like to ask you another question. As for the loss function of the decoder ConvKB, you used torch.nn.SoftMarginLoss() in the code, but as far as I know, this function is exp(-y * x), while there is no negative sign in the loss function of ConvKB. Would you please answer for me?
