### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 3.81 GiB (GPU 0; 11.17 GiB total capacity; 3.94 GiB already allocated; 2.65 GiB free; 33.35 MiB cached)

### ISSUE THREAD

**Issue by BittersweetJ** [deepakn97/relationPrediction#13]
Thank you very much for your work in this paper. I also tried to run your code, but there has been a problem of insufficient GPU capacity. I want to ask how much GPU capacity your code requires?I look forward to receiving your reply as soon as possible. Thank you

**Comment by chauhanjatin10** [comment]
Hi @BittersweetJ , thanks for showing interest in our work. Our code can require upto 12 GB memory during the decoder phase. You can adjust it by decreasing the batch size, however the model performance may change accordingly.
