### ISSUE TITLE
Cannot run FB15k-237 dataset on 16G GPU using default parameters provided by the author

### ISSUE THREAD

**Issue by gecongcong** [deepakn97/relationPrediction#16]
number of unique_entities -> 14505
number of unique_entities -> 9809
number of unique_entities -> 10348
Initialised relations and entities from TransE
Total triples count 310116, training triples 272115, validation_triples 17535, test_triples 20466
Opening node_neighbors pickle object
Initial entity dimensions torch.Size([14541, 100]) , relation dimensions torch.Size([237, 100])
Defining model

Model type -> GAT layer with 2 heads used, Initial Embeddings training
length of unique_entities  14505
Number of epochs 3000

epoch->  0
Traceback (most recent call last):
  File "/root/zc/GAT2019ACL/main.py", line 366, in <module>
    train_gat(args)
  File "/root/zc/GAT2019ACL/main.py", line 235, in train_gat
    Corpus_, Corpus_.train_adj_matrix, train_indices, current_batch_2hop_indices)
  File "/root/embedding-venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/zc/GAT2019ACL/models.py", line 141, in forward
    edge_list, edge_type, edge_embed, edge_list_nhop, edge_type_nhop)
  File "/root/embedding-venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/zc/GAT2019ACL/models.py", line 52, in forward
    edge_type_nhop[:, 0]] + relation_embed[edge_type_nhop[:, 1]]
RuntimeError: CUDA out of memory. Tried to allocate 4.77 GiB (GPU 0; 15.90 GiB total capacity; 10.44 GiB already allocated; 4.73 GiB free; 32.66 MiB cached)

Process finished with exit code 1

**Comment by gecongcong** [comment]
I want to know how much GPU memory is needed in the encoder stage

**Comment by deepakn97** [comment]
Memory usage depends on many factors. It can vary across different GPUs. In our case, it take aroung 9GB memory while running on Titan Xp and around 6.5GB memory while running on RTX 2070 Super. 
It can also vary depending on the version of cudnn you are using. You can read more about it here:
https://discuss.pytorch.org/t/a-huge-difference-of-memory-usage-on-different-gpus/12410/5
I am closing this issue, if you have any other questions please feel free to re-open it. 
Sorry for the extremely late reply.
