### ISSUE TITLE
Test on different data

### ISSUE THREAD

**Issue by karinseve** [deepakn97/relationPrediction#18]
I want to test your model, say trained on WN, on a different dataset.
Is there a simple way to do this? I'm looking at your code but it seems like it requires a lot of edits.

Thank you!

**Comment by deepakn97** [comment]
Hey,
Please see if "Reproducing Results" section in this [article](https://deepakn97.github.io/blog/2019/Knowledge-Base-Relation-Prediction/) helps you.
Basically you need to create 3 files with a similar directory structure to existing datasets. 
Sorry for the extremely delayed response.

**Comment by deepakn97** [comment]
Hey
Closing this issue. Please feel free to reopen.
