### ISSUE TITLE
What is the role of "headTailSelector" in preprocess.py?

### ISSUE THREAD

**Issue by BittersweetJ** [deepakn97/relationPrediction#19]
headTailSelector = {}
    for i in range(len(relation2id)):
        headTailSelector[i] = 1000 * right_entity_avg[i] /  (right_entity_avg[i] + left_entity_avg[i])

I hope you can reply me as soon as possible.Thank you very much!

**Comment by roholazandie** [comment]
If you track down the code they don't really use it. So you can safely ignore it

**Comment by chauhanjatin10** [comment]
Hi @BittersweetJ. This was taken from pre-processing script of the implementation of the original ConvKB paper. This is used for choosing either to replace the head entity or the tail entity when constructing the negative triples. For our work, we have used both types of replacements simultaneously. Hence you can ignore this. 
@roholazandie, I thank you once again for the all the responses to the issues the readers have raised.
Thanks.
