### ISSUE TITLE
in this part, the loss indicate that your model will let pos triplet have high norm, while neg trilet have low norm. This is just contrast to transe which pos triplet have low norm.

### ISSUE THREAD

**Issue by namenotexist** [deepakn97/relationPrediction#21]
![image](https://user-images.githubusercontent.com/40298904/79037057-959a8f00-7c00-11ea-80fe-bb8123991089.png)

**Comment by zhazhadi** [comment]
I found the same problem, and the source code is also implemented in this way, which is ridiculous!

**Comment by roholazandie** [comment]
We are not even sure this code exactly replicate the reported numbers in the paper as pointed out by others!

**Comment by chauhanjatin10** [comment]
Hi @namenotexist , @zhazhadi , @roholazandie . Thanks for showing interest in our work and also pointing out this issue. We thoroughly apologize for the late reply and not having updated the repository(both the authors are busy with their works). The code has been corrected by negating the label tensor in line 159 of the main.py file. You can now reproduce the results. Once again, I apologize on behalf of all the authors for responding this late.

**Comment by chauhanjatin10** [comment]
Equation 13 in the main paper will be updated soon. I am closing this issue.
Thanks
