### ISSUE TITLE
how long does it take to get 2_hop.

### ISSUE THREAD

**Issue by HagridThick** [deepakn97/relationPrediction#24]
i run the command:  python main.py --get_2hop True
it returns:
number of unique_entities -> 40559
number of unique_entities -> 5173
number of unique_entities -> 5323
Initialised relations and entities from TransE
Graph created
length of graph keys is  39610

and it feels stuck.
want to know how long it takes. and whether it return message to let me know its done.

**Comment by deepakn97** [comment]
Hi 
It will take around 45 mins to generate all 2-hops for FB15k-237 dataset. Once the process completes, the training will start so you will know that it is completed.
Closing this issue.
