### ISSUE TITLE
Raw or Filter

### ISSUE THREAD

**Issue by makabaka987** [deepakn97/relationPrediction#26]
Thank you for your codes! I would like to ask you whether the negative samples are really filtered during the experiment. The negative sampling formula in the paper does not reflect filtering, but the code seems to implement filtering.

**Comment by chauhanjatin10** [comment]
Hi @wangyishuo . Thanks for showing interest in our work. We have performed negative sampling in the code in this line - https://github.com/deepakn97/relationPrediction/blob/afc0d5ca05f44f5b0ad6525d612f2d5e1d8811ae/create_batch.py#L84 . Yes, we haven't explicitly mentioned about the filtering process in the paper, but its being performed as you have already checked in the code by randomly creating a triple not the in the training triples list. I hope this clarifies.
Regards 
Jatin
