### ISSUE TITLE
A question about attention code

### ISSUE THREAD

**Issue by liuxiyang641** [deepakn97/relationPrediction#31]
What does that mean by setting -leakrelu and rowsum[rowwum=0]=1e-12 ?
```python
powers = -self.leakyrelu(self.a_2.mm(edge_m).squeeze())
e_rowsum = self.special_spmm_final(
            edge, edge_e, N, edge_e.shape[0], 1)
e_rowsum[e_rowsum == 0.0] = 1e-12
```
I just can't understand why there is a negative sign of `leakrelu` and `1e-12` for `e_rowsum`.
Looking for forward to your reply. @deepakn97

**Comment by deepakn97** [comment]
@liuxiyang641 The negative sign in front leakyrelu was to avoid any numerical instability, but the code works without it as well. It was to be checked later but never got to it. 
For the second question, we use e_rowsum[e_rowsum == 0.0] = 1e-12 to replace all the zero values with low negative value so as to avoid division by 0 which will result in NaN. 
I hope I have answered your question. Please close the issue if you don't have any more concerns.

**Comment by liuxiyang641** [comment]
I got it. Thanks for your kind reply.
