### ISSUE TITLE
How long does it take to run on a dataset

### ISSUE THREAD

**Issue by caoh18** [deepakn97/relationPrediction#4]
Hi, thank you for your code! I am trying to run it on FB15k-237. But it get stuck at "Graph created length of graph keys is  13781" for a long time. Is this normal or not? Besides, how long does it take to run on a single dataset?  Thanks in advance!

**Comment by snsxf** [comment]
I got the same problem. Just modified the bfs() in create_batch.py,   add
            "if distance[top[0]] == nbd_size: continue"
after 
           "top = q.get()"

**Comment by deepakn97** [comment]
It is supposed to make a list of all 2-hop neighbors for all entities, so it takes time. This only happens the first time you run the code. On FB15k-237, with default parameters, it should take around 10-11 hours to run.

**Comment by chrislouis0106** [comment]
I want to point out that bfs() in create_batch.py is not able to traverse all 2-hop paths for all entities. It only includes partial 2-hop paths, and the key problem exists in the 273 line of create_batch.py.
