### ISSUE TITLE
Reproduced results are a little lesser than those in the paper for FB15k-237 dataset

### ISSUE THREAD

**Issue by prakhar6sharma** [deepakn97/relationPrediction#5]
Reproducing the results with the hyperparameters mentioned in the repo and even with other variations produced a max MRR of 0.451 but the claimed MRR in paper is 0.518.
Is This expected or am I missing something.

**Comment by chauhanjatin10** [comment]
Hi. Can you post the results you obtained for all the metrics on freebase? There is some issue with code. We will fix this soon. Apologies for the inconvenience caused.

**Comment by foreseez** [comment]
> Hi. Can you post the results you obtained for all the metrics on freebase? There is some issue with code. We will fix this soon. Apologies for the inconvenience caused.

excuse me  have you fix the code now?  if you are convenient ，can you disclose your update code?

**Comment by chenwang1701** [comment]
> Reproducing the results with the hyperparameters mentioned in the repo and even with other variations produced a max MRR of 0.451 but the claimed MRR in paper is 0.518.
> Is This expected or am I missing something.
So could you reproduce the  model now?  And how about the results on FB15K237? Is there really so great improvement?

**Comment by chenwang1701** [comment]
> Reproducing the results with the hyperparameters mentioned in the repo and even with other variations produced a max MRR of 0.451 but the claimed MRR in paper is 0.518.
> Is This expected or am I missing something.

So could you reproduce the model now? How about the results on FB15K237?  Is there really so huge improment?

**Comment by kgresearch** [comment]
How soon will you  update your FB15k237 score with bug fixed?

**Comment by pp413** [comment]
Averaged stats for replacing head are -> 
Hits@100 are 0.7768861923867306
Hits@10 are 0.5745669830707506
Hits@3 are 0.45748116254036597
Hits@1 are 0.3560035228495939
Mean rank 224.58694588511597
Mean Reciprocal Rank 0.42924094232196497

Averaged stats for replacing tail are -> 
Hits@100 are 0.8098150503963206
Hits@10 are 0.605979058616303
Hits@3 are 0.4826793228300225
Hits@1 are 0.3767491926803014
Mean rank 175.6919953028672
Mean Reciprocal Rank 0.45338468520343606

Cumulative stats are -> 
Hits@100 are 0.7933506213915256
Hits@10 are 0.5902730208435267
Hits@3 are 0.4700802426851942
Hits@1 are 0.36637635776494765
Mean rank 200.13947059399158
Mean Reciprocal Rank 0.4413128137627005

The above scores of FB15k-237 are getting from your method, but I only use the ConvKB and obtain the scores as well as your original codes.

**Comment by chenwang1701** [comment]
Deer Long,

The results are a little lower than the reported in KBGAT, so you use the constant initialization [0.1,0.1m-0.1 ] for the filter of the convolution layer for FB15K237? I found that constant initialization is essential for FB15k237, which could improve about 3 percent on MRR.

Best Regards.



At 2019-12-13 09:12:33, "YaoShuang-long" <notifications@github.com> wrote:

Averaged stats for replacing head are ->
Hits@100 are 0.7768861923867306
Hits@10 are 0.5745669830707506
Hits@3 are 0.45748116254036597
Hits@1 are 0.3560035228495939
Mean rank 224.58694588511597
Mean Reciprocal Rank 0.42924094232196497

Averaged stats for replacing tail are ->
Hits@100 are 0.8098150503963206
Hits@10 are 0.605979058616303
Hits@3 are 0.4826793228300225
Hits@1 are 0.3767491926803014
Mean rank 175.6919953028672
Mean Reciprocal Rank 0.45338468520343606

Cumulative stats are ->
Hits@100 are 0.7933506213915256
Hits@10 are 0.5902730208435267
Hits@3 are 0.4700802426851942
Hits@1 are 0.36637635776494765
Mean rank 200.13947059399158
Mean Reciprocal Rank 0.4413128137627005

The above scores of FB15k-237 are getting from your method, but I only use the ConvKB and obtain the scores as well as your original codes.

**Comment by chauhanjatin10** [comment]
Hi,
The bug has been fixed.

**Comment by junkangwu** [comment]
> Hi,
> The bug has been fixed.



Really？ I still can not reproduce the results. 
Current iteration time 1850.3510513305664
Stats for replacing head are -> 
Current iteration Hits@100 are 0.7879929543008122
Current iteration Hits@10 are 0.5855269595850866
Current iteration Hits@3 are 0.46457579019473527
Current iteration Hits@1 are 0.34744104119776886
Current iteration Mean rank 206.47529112437616
Current iteration Mean Reciprocal Rank 0.42885591542954055

Stats for replacing tail are -> 
Current iteration Hits@100 are 0.8246403757706233
Current iteration Hits@10 are 0.6212447401898424
Current iteration Hits@3 are 0.49427536940992267
Current iteration Hits@1 are 0.3760641941481554
Current iteration Mean rank 169.4703004207848
Current iteration Mean Reciprocal Rank 0.4589613123827825

Averaged stats for replacing head are -> 
Hits@100 are 0.7879929543008122
Hits@10 are 0.5855269595850866
Hits@3 are 0.46457579019473527
Hits@1 are 0.34744104119776886
Mean rank 206.47529112437616
Mean Reciprocal Rank 0.42885591542954055

Averaged stats for replacing tail are -> 
Hits@100 are 0.8246403757706233
Hits@10 are 0.6212447401898424
Hits@3 are 0.49427536940992267
Hits@1 are 0.3760641941481554
Mean rank 169.4703004207848
Mean Reciprocal Rank 0.4589613123827825

Cumulative stats are -> 
Hits@100 are 0.8063166650357178
Hits@10 are 0.6033858498874645
Hits@3 are 0.47942557980232897
Hits@1 are 0.36175261767296213
Mean rank 187.97279577258047
Mean Reciprocal Rank 0.44390861390616154
