### ISSUE TITLE
number of GAT layers

### ISSUE THREAD

**Issue by xiang-deng** [deepakn97/relationPrediction#6]
Hi, thank you for sharing the code. 
From the description in the paper, the model has more than 1 layer of GAT, what is the number of layers used for the result reported in the paper? I don't find it in the supplementary section. In the code, seems it's just single layer

**Comment by zysforever** [comment]
> Hi, thank you for sharing the code.
> From the description in the paper, the model has more than 1 layer of GAT, what is the number of layers used for the result reported in the paper? I don't find it in the supplementary section. In the code, seems it's just single layer

The number of GAT layers in the code and paper is both 2. You can see the "use_2hop" parameter.

**Comment by deepakn97** [comment]
We use 2 GAT layers as mentioned in the Paper. You can see this in the models.py file.
I am closing this issue, please feel free to re-open it in case you have any issue.
Sorry for extremely late reply.
