### ISSUE TITLE
Error: CUDA out of memory.

### ISSUE THREAD

**Issue by AriessHosizora** [deepakn97/relationPrediction#7]
Hi , I get this error when I run the program :   CUDA out of memory.
Do you know how to solve this problem? My graphics card model is Nvidia 1080Ti.  What type of graphics card are you using ？

**Comment by deepakn97** [comment]
Hi, may I know when are you facing this issue? While running the algorithm or while installing the packages through conda?

**Comment by AriessHosizora** [comment]
I used a graphics card with a lot of memory and didn't have this problem

**Comment by chauhanjatin10** [comment]
Hi, @BOBOJUNLI. Thanks for showing interest in our paper. We used a P100 server with 12GB cuda memory. The parameters in the model were adjusted in accordance with much amount of memory. If your problem has been resolved, I would request you close the issue.
